export const CART_TOGGLE_HIDDEN = "CART_TOGGLE_HIDDEN";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_DECREASE_ITEM = "CART_DECREASE_ITEM";
